//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalResource.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalResource.Resources.LangText", typeof(LangText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Branch.
        /// </summary>
        public static string addBranch {
            get {
                return ResourceManager.GetString("addBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Counter.
        /// </summary>
        public static string addCounter {
            get {
                return ResourceManager.GetString("addCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Service.
        /// </summary>
        public static string addService {
            get {
                return ResourceManager.GetString("addService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocate Services to Counter.
        /// </summary>
        public static string allocateCounterService {
            get {
                return ResourceManager.GetString("allocateCounterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Configuration Portal.
        /// </summary>
        public static string applicationName {
            get {
                return ResourceManager.GetString("applicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string arName {
            get {
                return ResourceManager.GetString("arName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Branches.
        /// </summary>
        public static string backToBranches {
            get {
                return ResourceManager.GetString("backToBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Counters.
        /// </summary>
        public static string backToCounters {
            get {
                return ResourceManager.GetString("backToCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string backToList {
            get {
                return ResourceManager.GetString("backToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login page.
        /// </summary>
        public static string backToLogin {
            get {
                return ResourceManager.GetString("backToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string bankName {
            get {
                return ResourceManager.GetString("bankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string branch {
            get {
                return ResourceManager.GetString("branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string branches {
            get {
                return ResourceManager.GetString("branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your connection to the database.
        /// </summary>
        public static string checkConnection {
            get {
                return ResourceManager.GetString("checkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string counter {
            get {
                return ResourceManager.GetString("counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        public static string counters {
            get {
                return ResourceManager.GetString("counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Branch.
        /// </summary>
        public static string createBranch {
            get {
                return ResourceManager.GetString("createBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Counter.
        /// </summary>
        public static string createCounter {
            get {
                return ResourceManager.GetString("createCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Service.
        /// </summary>
        public static string createService {
            get {
                return ResourceManager.GetString("createService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item ?.
        /// </summary>
        public static string deleteMsg {
            get {
                return ResourceManager.GetString("deleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Branch.
        /// </summary>
        public static string editBranch {
            get {
                return ResourceManager.GetString("editBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Counter.
        /// </summary>
        public static string editCounter {
            get {
                return ResourceManager.GetString("editCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Service.
        /// </summary>
        public static string editService {
            get {
                return ResourceManager.GetString("editService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string enName {
            get {
                return ResourceManager.GetString("enName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic name field required.
        /// </summary>
        public static string errorArName {
            get {
                return ResourceManager.GetString("errorArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank field required.
        /// </summary>
        public static string errorBankName {
            get {
                return ResourceManager.GetString("errorBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request.
        /// </summary>
        public static string errorDetail {
            get {
                return ResourceManager.GetString("errorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name field required.
        /// </summary>
        public static string errorEnName {
            get {
                return ResourceManager.GetString("errorEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length must be less than 100 character.
        /// </summary>
        public static string errorMax {
            get {
                return ResourceManager.GetString("errorMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string errorMsg {
            get {
                return ResourceManager.GetString("errorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field required.
        /// </summary>
        public static string errorPassword {
            get {
                return ResourceManager.GetString("errorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket value must be between 1 - 100.
        /// </summary>
        public static string errorRange {
            get {
                return ResourceManager.GetString("errorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket field required.
        /// </summary>
        public static string errorTickets {
            get {
                return ResourceManager.GetString("errorTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type field required.
        /// </summary>
        public static string errorType {
            get {
                return ResourceManager.GetString("errorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-name field required.
        /// </summary>
        public static string errorUserName {
            get {
                return ResourceManager.GetString("errorUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone already delete this item.
        /// </summary>
        public static string itemDeleted {
            get {
                return ResourceManager.GetString("itemDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string languageText {
            get {
                return ResourceManager.GetString("languageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name, username or password is not correct.
        /// </summary>
        public static string loginMessage {
            get {
                return ResourceManager.GetString("loginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Data.
        /// </summary>
        public static string saveData {
            get {
                return ResourceManager.GetString("saveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Service Name.
        /// </summary>
        public static string serviceArName {
            get {
                return ResourceManager.GetString("serviceArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Service Name.
        /// </summary>
        public static string serviceEnName {
            get {
                return ResourceManager.GetString("serviceEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign-Out.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
    }
}
